{
  if (TestTransactions.doFail && random().nextInt() % 10 <= 3) {
    throw new IOException("now failing randomly but on purpose");
  }
}
