{
  Throwable e=disaster;
  if (e instanceof AlreadyClosedException) {
    e=e.getCause();
  }
  if (e instanceof OutOfMemoryError && e.getMessage() != null && e.getMessage().startsWith("Fake OutOfMemoryError")) {
    log.println("\nTEST: got expected fake exc:" + e.getMessage());
    e.printStackTrace(log);
    try {
      writer.rollback();
    }
 catch (    Throwable t) {
    }
    return (OutOfMemoryError)e;
  }
 else {
    Rethrow.rethrow(disaster);
    return null;
  }
}
