{
  try {
    callable.call(data);
  }
 catch (  Exception e) {
    log.error("TEST HOOK EXCEPTION",e);
  }
}
