{
  try {
    callable.call(data);
  }
 catch (  Throwable th) {
    log.error("TEST HOOK EXCEPTION",th);
  }
}
