{
  try {
    this._run();
  }
 catch (  final Throwable t) {
    failed=true;
    throw new RuntimeException(t);
  }
}
